/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MensagensAgendadasRouteImport } from './routes/mensagens-agendadas'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EquipeLojaRouteImport } from './routes/equipe-loja'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CaixaPdvRouteImport } from './routes/caixa-pdv'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasSimuladorRouteImport } from './routes/vendas.simulador'
import { Route as VendasOrcamentosRouteImport } from './routes/vendas.orcamentos'
import { Route as VendasHistoricoRouteImport } from './routes/vendas.historico'
import { Route as VendasGarantiasRouteImport } from './routes/vendas.garantias'
import { Route as VendasDeliveryRouteImport } from './routes/vendas.delivery'
import { Route as VendasConsultaEstoqueRouteImport } from './routes/vendas.consulta-estoque'
import { Route as VendasCalculadoraRouteImport } from './routes/vendas.calculadora'
import { Route as ServicosTermosRouteImport } from './routes/servicos.termos'
import { Route as ServicosTecnicosRouteImport } from './routes/servicos.tecnicos'
import { Route as ServicosNovaRouteImport } from './routes/servicos.nova'
import { Route as ServicosDashboardRouteImport } from './routes/servicos.dashboard'
import { Route as ServicosChecklistsRouteImport } from './routes/servicos.checklists'
import { Route as RelatoriosVipRouteImport } from './routes/relatorios.vip'
import { Route as RelatoriosCrescimentoRouteImport } from './routes/relatorios.crescimento'
import { Route as RelatoriosComissoesRouteImport } from './routes/relatorios.comissoes'
import { Route as RelatoriosChurnRouteImport } from './routes/relatorios.churn'
import { Route as ReciboIdRouteImport } from './routes/recibo.$id'
import { Route as OsTrackIdRouteImport } from './routes/os-track.$id'
import { Route as OsTermoIdRouteImport } from './routes/os-termo.$id'
import { Route as OrcamentoIdRouteImport } from './routes/orcamento.$id'
import { Route as MinhaContaSegurancaRouteImport } from './routes/minha-conta.seguranca'
import { Route as MinhaContaLgpdRouteImport } from './routes/minha-conta.lgpd'
import { Route as MAtendimentoRouteImport } from './routes/m.atendimento'
import { Route as FinanceiroPlanoContasRouteImport } from './routes/financeiro.plano-contas'
import { Route as FinanceiroNotasAbertoRouteImport } from './routes/financeiro.notas-aberto'
import { Route as FinanceiroMaquininhasRouteImport } from './routes/financeiro.maquininhas'
import { Route as FinanceiroFornecedoresRouteImport } from './routes/financeiro.fornecedores'
import { Route as FinanceiroDreRouteImport } from './routes/financeiro.dre'
import { Route as FinanceiroCaixaRouteImport } from './routes/financeiro.caixa'
import { Route as EstoqueVendidosRouteImport } from './routes/estoque.vendidos'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque.movimentacoes'
import { Route as EstoqueEtiquetasRouteImport } from './routes/estoque.etiquetas'
import { Route as EstoqueComprasRouteImport } from './routes/estoque.compras'
import { Route as EstoqueAtualRouteImport } from './routes/estoque.atual'
import { Route as CrmConversasRouteImport } from './routes/crm_.conversas'
import { Route as CrmCatalogoRouteImport } from './routes/crm_.catalogo'
import { Route as CrmBotRouteImport } from './routes/crm_.bot'
import { Route as ConviteLojaTokenRouteImport } from './routes/convite-loja.$token'
import { Route as ConfiguracoesLojaRouteImport } from './routes/configuracoes.loja'
import { Route as ApiExportDataRouteImport } from './routes/api/export-data'
import { Route as ApiAdminMetricsRouteImport } from './routes/api/admin-metrics'
import { Route as AceitarConviteTokenRouteImport } from './routes/aceitar-convite.$token'
import { Route as ApiReceiptIdRouteImport } from './routes/api/receipt.$id'
import { Route as ApiQuoteIdRouteImport } from './routes/api/quote.$id'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public.$'
import { Route as ApiOsPublicIdRouteImport } from './routes/api/os-public.$id'
import { Route as ApiEvolutionSplatRouteImport } from './routes/api/evolution/$'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/whatsapp.lazy').then((d) => d.Route))
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensAgendadasRoute = MensagensAgendadasRouteImport.update({
  id: '/mensagens-agendadas',
  path: '/mensagens-agendadas',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeLojaRoute = EquipeLojaRouteImport.update({
  id: '/equipe-loja',
  path: '/equipe-loja',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaPdvRoute = CaixaPdvRouteImport.update({
  id: '/caixa-pdv',
  path: '/caixa-pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasSimuladorRoute = VendasSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => VendasRoute,
} as any)
const VendasOrcamentosRoute = VendasOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => VendasRoute,
} as any)
const VendasHistoricoRoute = VendasHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => VendasRoute,
} as any)
const VendasGarantiasRoute = VendasGarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => VendasRoute,
} as any)
const VendasDeliveryRoute = VendasDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => VendasRoute,
} as any)
const VendasConsultaEstoqueRoute = VendasConsultaEstoqueRouteImport.update({
  id: '/consulta-estoque',
  path: '/consulta-estoque',
  getParentRoute: () => VendasRoute,
} as any)
const VendasCalculadoraRoute = VendasCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => VendasRoute,
} as any)
const ServicosTermosRoute = ServicosTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosTecnicosRoute = ServicosTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosNovaRoute = ServicosNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosDashboardRoute = ServicosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosChecklistsRoute = ServicosChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => ServicosRoute,
} as any)
const RelatoriosVipRoute = RelatoriosVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosCrescimentoRoute = RelatoriosCrescimentoRouteImport.update({
  id: '/crescimento',
  path: '/crescimento',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosComissoesRoute = RelatoriosComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosChurnRoute = RelatoriosChurnRouteImport.update({
  id: '/churn',
  path: '/churn',
  getParentRoute: () => RelatoriosRoute,
} as any)
const ReciboIdRoute = ReciboIdRouteImport.update({
  id: '/recibo/$id',
  path: '/recibo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OsTrackIdRoute = OsTrackIdRouteImport.update({
  id: '/os-track/$id',
  path: '/os-track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OsTermoIdRoute = OsTermoIdRouteImport.update({
  id: '/os-termo/$id',
  path: '/os-termo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoIdRoute = OrcamentoIdRouteImport.update({
  id: '/orcamento/$id',
  path: '/orcamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaSegurancaRoute = MinhaContaSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaLgpdRoute = MinhaContaLgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MAtendimentoRoute = MAtendimentoRouteImport.update({
  id: '/m/atendimento',
  path: '/m/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPlanoContasRoute = FinanceiroPlanoContasRouteImport.update({
  id: '/plano-contas',
  path: '/plano-contas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroNotasAbertoRoute = FinanceiroNotasAbertoRouteImport.update({
  id: '/notas-aberto',
  path: '/notas-aberto',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroMaquininhasRoute = FinanceiroMaquininhasRouteImport.update({
  id: '/maquininhas',
  path: '/maquininhas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFornecedoresRoute = FinanceiroFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDreRoute = FinanceiroDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroCaixaRoute = FinanceiroCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => FinanceiroRoute,
} as any)
const EstoqueVendidosRoute = EstoqueVendidosRouteImport.update({
  id: '/vendidos',
  path: '/vendidos',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueEtiquetasRoute = EstoqueEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueComprasRoute = EstoqueComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueAtualRoute = EstoqueAtualRouteImport.update({
  id: '/atual',
  path: '/atual',
  getParentRoute: () => EstoqueRoute,
} as any)
const CrmConversasRoute = CrmConversasRouteImport.update({
  id: '/crm_/conversas',
  path: '/crm/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCatalogoRoute = CrmCatalogoRouteImport.update({
  id: '/crm_/catalogo',
  path: '/crm/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmBotRoute = CrmBotRouteImport.update({
  id: '/crm_/bot',
  path: '/crm/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteLojaTokenRoute = ConviteLojaTokenRouteImport.update({
  id: '/convite-loja/$token',
  path: '/convite-loja/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesLojaRoute = ConfiguracoesLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ApiExportDataRoute = ApiExportDataRouteImport.update({
  id: '/api/export-data',
  path: '/api/export-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMetricsRoute = ApiAdminMetricsRouteImport.update({
  id: '/api/admin-metrics',
  path: '/api/admin-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteTokenRoute = AceitarConviteTokenRouteImport.update({
  id: '/aceitar-convite/$token',
  path: '/aceitar-convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptIdRoute = ApiReceiptIdRouteImport.update({
  id: '/api/receipt/$id',
  path: '/api/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteIdRoute = ApiQuoteIdRouteImport.update({
  id: '/api/quote/$id',
  path: '/api/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOsPublicIdRoute = ApiOsPublicIdRouteImport.update({
  id: '/api/os-public/$id',
  path: '/api/os-public/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionSplatRoute = ApiEvolutionSplatRouteImport.update({
  id: '/api/evolution/$',
  path: '/api/evolution/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/agentes': typeof AgentesRoute
  '/api-keys': typeof ApiKeysRoute
  '/assinar': typeof AssinarRoute
  '/atendimento': typeof AtendimentoRoute
  '/audit-log': typeof AuditLogRoute
  '/automacao': typeof AutomacaoRoute
  '/automacoes': typeof AutomacoesRoute
  '/broadcast': typeof BroadcastRoute
  '/caixa-pdv': typeof CaixaPdvRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/equipe-loja': typeof EquipeLojaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/integracoes': typeof IntegracoesRoute
  '/inventario': typeof InventarioRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/mensagens-agendadas': typeof MensagensAgendadasRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/pipeline': typeof PipelineRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/api/admin-metrics': typeof ApiAdminMetricsRoute
  '/api/export-data': typeof ApiExportDataRoute
  '/configuracoes/loja': typeof ConfiguracoesLojaRoute
  '/convite-loja/$token': typeof ConviteLojaTokenRoute
  '/crm/bot': typeof CrmBotRoute
  '/crm/catalogo': typeof CrmCatalogoRoute
  '/crm/conversas': typeof CrmConversasRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/notas-aberto': typeof FinanceiroNotasAbertoRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/m/atendimento': typeof MAtendimentoRoute
  '/minha-conta/lgpd': typeof MinhaContaLgpdRoute
  '/minha-conta/seguranca': typeof MinhaContaSegurancaRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/os-termo/$id': typeof OsTermoIdRoute
  '/os-track/$id': typeof OsTrackIdRoute
  '/recibo/$id': typeof ReciboIdRoute
  '/relatorios/churn': typeof RelatoriosChurnRoute
  '/relatorios/comissoes': typeof RelatoriosComissoesRoute
  '/relatorios/crescimento': typeof RelatoriosCrescimentoRoute
  '/relatorios/vip': typeof RelatoriosVipRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/api/os-public/$id': typeof ApiOsPublicIdRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/quote/$id': typeof ApiQuoteIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/agentes': typeof AgentesRoute
  '/api-keys': typeof ApiKeysRoute
  '/assinar': typeof AssinarRoute
  '/atendimento': typeof AtendimentoRoute
  '/audit-log': typeof AuditLogRoute
  '/automacao': typeof AutomacaoRoute
  '/automacoes': typeof AutomacoesRoute
  '/broadcast': typeof BroadcastRoute
  '/caixa-pdv': typeof CaixaPdvRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/equipe-loja': typeof EquipeLojaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/integracoes': typeof IntegracoesRoute
  '/inventario': typeof InventarioRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/mensagens-agendadas': typeof MensagensAgendadasRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/pipeline': typeof PipelineRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/api/admin-metrics': typeof ApiAdminMetricsRoute
  '/api/export-data': typeof ApiExportDataRoute
  '/configuracoes/loja': typeof ConfiguracoesLojaRoute
  '/convite-loja/$token': typeof ConviteLojaTokenRoute
  '/crm/bot': typeof CrmBotRoute
  '/crm/catalogo': typeof CrmCatalogoRoute
  '/crm/conversas': typeof CrmConversasRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/notas-aberto': typeof FinanceiroNotasAbertoRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/m/atendimento': typeof MAtendimentoRoute
  '/minha-conta/lgpd': typeof MinhaContaLgpdRoute
  '/minha-conta/seguranca': typeof MinhaContaSegurancaRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/os-termo/$id': typeof OsTermoIdRoute
  '/os-track/$id': typeof OsTrackIdRoute
  '/recibo/$id': typeof ReciboIdRoute
  '/relatorios/churn': typeof RelatoriosChurnRoute
  '/relatorios/comissoes': typeof RelatoriosComissoesRoute
  '/relatorios/crescimento': typeof RelatoriosCrescimentoRoute
  '/relatorios/vip': typeof RelatoriosVipRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/api/os-public/$id': typeof ApiOsPublicIdRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/quote/$id': typeof ApiQuoteIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/agentes': typeof AgentesRoute
  '/api-keys': typeof ApiKeysRoute
  '/assinar': typeof AssinarRoute
  '/atendimento': typeof AtendimentoRoute
  '/audit-log': typeof AuditLogRoute
  '/automacao': typeof AutomacaoRoute
  '/automacoes': typeof AutomacoesRoute
  '/broadcast': typeof BroadcastRoute
  '/caixa-pdv': typeof CaixaPdvRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/equipe-loja': typeof EquipeLojaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/instagram': typeof InstagramRoute
  '/integracoes': typeof IntegracoesRoute
  '/inventario': typeof InventarioRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/mensagens-agendadas': typeof MensagensAgendadasRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/nps': typeof NpsRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/pipeline': typeof PipelineRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/api/admin-metrics': typeof ApiAdminMetricsRoute
  '/api/export-data': typeof ApiExportDataRoute
  '/configuracoes/loja': typeof ConfiguracoesLojaRoute
  '/convite-loja/$token': typeof ConviteLojaTokenRoute
  '/crm_/bot': typeof CrmBotRoute
  '/crm_/catalogo': typeof CrmCatalogoRoute
  '/crm_/conversas': typeof CrmConversasRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/notas-aberto': typeof FinanceiroNotasAbertoRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/m/atendimento': typeof MAtendimentoRoute
  '/minha-conta/lgpd': typeof MinhaContaLgpdRoute
  '/minha-conta/seguranca': typeof MinhaContaSegurancaRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
  '/os-termo/$id': typeof OsTermoIdRoute
  '/os-track/$id': typeof OsTrackIdRoute
  '/recibo/$id': typeof ReciboIdRoute
  '/relatorios/churn': typeof RelatoriosChurnRoute
  '/relatorios/comissoes': typeof RelatoriosComissoesRoute
  '/relatorios/crescimento': typeof RelatoriosCrescimentoRoute
  '/relatorios/vip': typeof RelatoriosVipRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/api/os-public/$id': typeof ApiOsPublicIdRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/quote/$id': typeof ApiQuoteIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/agentes'
    | '/api-keys'
    | '/assinar'
    | '/atendimento'
    | '/audit-log'
    | '/automacao'
    | '/automacoes'
    | '/broadcast'
    | '/caixa-pdv'
    | '/calendario'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/equipe-loja'
    | '/esqueci-senha'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/help'
    | '/inbox'
    | '/instagram'
    | '/integracoes'
    | '/inventario'
    | '/leads'
    | '/login'
    | '/lojas'
    | '/mensagens-agendadas'
    | '/minha-conta'
    | '/nps'
    | '/onboarding'
    | '/painel'
    | '/pdv'
    | '/pipeline'
    | '/planos'
    | '/privacidade'
    | '/produtos'
    | '/registro'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/status'
    | '/templates'
    | '/termos'
    | '/vendas'
    | '/whatsapp'
    | '/aceitar-convite/$token'
    | '/api/admin-metrics'
    | '/api/export-data'
    | '/configuracoes/loja'
    | '/convite-loja/$token'
    | '/crm/bot'
    | '/crm/catalogo'
    | '/crm/conversas'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/notas-aberto'
    | '/financeiro/plano-contas'
    | '/m/atendimento'
    | '/minha-conta/lgpd'
    | '/minha-conta/seguranca'
    | '/orcamento/$id'
    | '/os-termo/$id'
    | '/os-track/$id'
    | '/recibo/$id'
    | '/relatorios/churn'
    | '/relatorios/comissoes'
    | '/relatorios/crescimento'
    | '/relatorios/vip'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/api/evolution/$'
    | '/api/os-public/$id'
    | '/api/public/$'
    | '/api/quote/$id'
    | '/api/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/agentes'
    | '/api-keys'
    | '/assinar'
    | '/atendimento'
    | '/audit-log'
    | '/automacao'
    | '/automacoes'
    | '/broadcast'
    | '/caixa-pdv'
    | '/calendario'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/equipe-loja'
    | '/esqueci-senha'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/help'
    | '/inbox'
    | '/instagram'
    | '/integracoes'
    | '/inventario'
    | '/leads'
    | '/login'
    | '/lojas'
    | '/mensagens-agendadas'
    | '/minha-conta'
    | '/nps'
    | '/onboarding'
    | '/painel'
    | '/pdv'
    | '/pipeline'
    | '/planos'
    | '/privacidade'
    | '/produtos'
    | '/registro'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/status'
    | '/templates'
    | '/termos'
    | '/vendas'
    | '/whatsapp'
    | '/aceitar-convite/$token'
    | '/api/admin-metrics'
    | '/api/export-data'
    | '/configuracoes/loja'
    | '/convite-loja/$token'
    | '/crm/bot'
    | '/crm/catalogo'
    | '/crm/conversas'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/notas-aberto'
    | '/financeiro/plano-contas'
    | '/m/atendimento'
    | '/minha-conta/lgpd'
    | '/minha-conta/seguranca'
    | '/orcamento/$id'
    | '/os-termo/$id'
    | '/os-track/$id'
    | '/recibo/$id'
    | '/relatorios/churn'
    | '/relatorios/comissoes'
    | '/relatorios/crescimento'
    | '/relatorios/vip'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/api/evolution/$'
    | '/api/os-public/$id'
    | '/api/public/$'
    | '/api/quote/$id'
    | '/api/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliados'
    | '/agentes'
    | '/api-keys'
    | '/assinar'
    | '/atendimento'
    | '/audit-log'
    | '/automacao'
    | '/automacoes'
    | '/broadcast'
    | '/caixa-pdv'
    | '/calendario'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/equipe-loja'
    | '/esqueci-senha'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/help'
    | '/inbox'
    | '/instagram'
    | '/integracoes'
    | '/inventario'
    | '/leads'
    | '/login'
    | '/lojas'
    | '/mensagens-agendadas'
    | '/minha-conta'
    | '/nps'
    | '/onboarding'
    | '/painel'
    | '/pdv'
    | '/pipeline'
    | '/planos'
    | '/privacidade'
    | '/produtos'
    | '/registro'
    | '/relatorios'
    | '/reset-password'
    | '/servicos'
    | '/status'
    | '/templates'
    | '/termos'
    | '/vendas'
    | '/whatsapp'
    | '/aceitar-convite/$token'
    | '/api/admin-metrics'
    | '/api/export-data'
    | '/configuracoes/loja'
    | '/convite-loja/$token'
    | '/crm_/bot'
    | '/crm_/catalogo'
    | '/crm_/conversas'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/notas-aberto'
    | '/financeiro/plano-contas'
    | '/m/atendimento'
    | '/minha-conta/lgpd'
    | '/minha-conta/seguranca'
    | '/orcamento/$id'
    | '/os-termo/$id'
    | '/os-track/$id'
    | '/recibo/$id'
    | '/relatorios/churn'
    | '/relatorios/comissoes'
    | '/relatorios/crescimento'
    | '/relatorios/vip'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/api/evolution/$'
    | '/api/os-public/$id'
    | '/api/public/$'
    | '/api/quote/$id'
    | '/api/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AgentesRoute: typeof AgentesRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AssinarRoute: typeof AssinarRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AuditLogRoute: typeof AuditLogRoute
  AutomacaoRoute: typeof AutomacaoRoute
  AutomacoesRoute: typeof AutomacoesRoute
  BroadcastRoute: typeof BroadcastRoute
  CaixaPdvRoute: typeof CaixaPdvRoute
  CalendarioRoute: typeof CalendarioRoute
  ClientesRoute: typeof ClientesRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  CrmRoute: typeof CrmRoute
  EquipeRoute: typeof EquipeRoute
  EquipeLojaRoute: typeof EquipeLojaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FiscalRoute: typeof FiscalRoute
  FunilRoute: typeof FunilRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  InstagramRoute: typeof InstagramRoute
  IntegracoesRoute: typeof IntegracoesRoute
  InventarioRoute: typeof InventarioRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  LojasRoute: typeof LojasRoute
  MensagensAgendadasRoute: typeof MensagensAgendadasRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  NpsRoute: typeof NpsRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRoute
  PdvRoute: typeof PdvRoute
  PipelineRoute: typeof PipelineRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  RegistroRoute: typeof RegistroRoute
  RelatoriosRoute: typeof RelatoriosRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  StatusRoute: typeof StatusRoute
  TemplatesRoute: typeof TemplatesRoute
  TermosRoute: typeof TermosRoute
  VendasRoute: typeof VendasRouteWithChildren
  WhatsappRoute: typeof WhatsappRoute
  AceitarConviteTokenRoute: typeof AceitarConviteTokenRoute
  ApiAdminMetricsRoute: typeof ApiAdminMetricsRoute
  ApiExportDataRoute: typeof ApiExportDataRoute
  ConviteLojaTokenRoute: typeof ConviteLojaTokenRoute
  CrmBotRoute: typeof CrmBotRoute
  CrmCatalogoRoute: typeof CrmCatalogoRoute
  CrmConversasRoute: typeof CrmConversasRoute
  MAtendimentoRoute: typeof MAtendimentoRoute
  OrcamentoIdRoute: typeof OrcamentoIdRoute
  OsTermoIdRoute: typeof OsTermoIdRoute
  OsTrackIdRoute: typeof OsTrackIdRoute
  ReciboIdRoute: typeof ReciboIdRoute
  ApiEvolutionSplatRoute: typeof ApiEvolutionSplatRoute
  ApiOsPublicIdRoute: typeof ApiOsPublicIdRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiQuoteIdRoute: typeof ApiQuoteIdRoute
  ApiReceiptIdRoute: typeof ApiReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens-agendadas': {
      id: '/mensagens-agendadas'
      path: '/mensagens-agendadas'
      fullPath: '/mensagens-agendadas'
      preLoaderRoute: typeof MensagensAgendadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-loja': {
      id: '/equipe-loja'
      path: '/equipe-loja'
      fullPath: '/equipe-loja'
      preLoaderRoute: typeof EquipeLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-pdv': {
      id: '/caixa-pdv'
      path: '/caixa-pdv'
      fullPath: '/caixa-pdv'
      preLoaderRoute: typeof CaixaPdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/simulador': {
      id: '/vendas/simulador'
      path: '/simulador'
      fullPath: '/vendas/simulador'
      preLoaderRoute: typeof VendasSimuladorRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/orcamentos': {
      id: '/vendas/orcamentos'
      path: '/orcamentos'
      fullPath: '/vendas/orcamentos'
      preLoaderRoute: typeof VendasOrcamentosRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/historico': {
      id: '/vendas/historico'
      path: '/historico'
      fullPath: '/vendas/historico'
      preLoaderRoute: typeof VendasHistoricoRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/garantias': {
      id: '/vendas/garantias'
      path: '/garantias'
      fullPath: '/vendas/garantias'
      preLoaderRoute: typeof VendasGarantiasRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/delivery': {
      id: '/vendas/delivery'
      path: '/delivery'
      fullPath: '/vendas/delivery'
      preLoaderRoute: typeof VendasDeliveryRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/consulta-estoque': {
      id: '/vendas/consulta-estoque'
      path: '/consulta-estoque'
      fullPath: '/vendas/consulta-estoque'
      preLoaderRoute: typeof VendasConsultaEstoqueRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/calculadora': {
      id: '/vendas/calculadora'
      path: '/calculadora'
      fullPath: '/vendas/calculadora'
      preLoaderRoute: typeof VendasCalculadoraRouteImport
      parentRoute: typeof VendasRoute
    }
    '/servicos/termos': {
      id: '/servicos/termos'
      path: '/termos'
      fullPath: '/servicos/termos'
      preLoaderRoute: typeof ServicosTermosRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/tecnicos': {
      id: '/servicos/tecnicos'
      path: '/tecnicos'
      fullPath: '/servicos/tecnicos'
      preLoaderRoute: typeof ServicosTecnicosRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/nova': {
      id: '/servicos/nova'
      path: '/nova'
      fullPath: '/servicos/nova'
      preLoaderRoute: typeof ServicosNovaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/dashboard': {
      id: '/servicos/dashboard'
      path: '/dashboard'
      fullPath: '/servicos/dashboard'
      preLoaderRoute: typeof ServicosDashboardRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/checklists': {
      id: '/servicos/checklists'
      path: '/checklists'
      fullPath: '/servicos/checklists'
      preLoaderRoute: typeof ServicosChecklistsRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/relatorios/vip': {
      id: '/relatorios/vip'
      path: '/vip'
      fullPath: '/relatorios/vip'
      preLoaderRoute: typeof RelatoriosVipRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/crescimento': {
      id: '/relatorios/crescimento'
      path: '/crescimento'
      fullPath: '/relatorios/crescimento'
      preLoaderRoute: typeof RelatoriosCrescimentoRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/comissoes': {
      id: '/relatorios/comissoes'
      path: '/comissoes'
      fullPath: '/relatorios/comissoes'
      preLoaderRoute: typeof RelatoriosComissoesRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/churn': {
      id: '/relatorios/churn'
      path: '/churn'
      fullPath: '/relatorios/churn'
      preLoaderRoute: typeof RelatoriosChurnRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/recibo/$id': {
      id: '/recibo/$id'
      path: '/recibo/$id'
      fullPath: '/recibo/$id'
      preLoaderRoute: typeof ReciboIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os-track/$id': {
      id: '/os-track/$id'
      path: '/os-track/$id'
      fullPath: '/os-track/$id'
      preLoaderRoute: typeof OsTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os-termo/$id': {
      id: '/os-termo/$id'
      path: '/os-termo/$id'
      fullPath: '/os-termo/$id'
      preLoaderRoute: typeof OsTermoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$id': {
      id: '/orcamento/$id'
      path: '/orcamento/$id'
      fullPath: '/orcamento/$id'
      preLoaderRoute: typeof OrcamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/seguranca': {
      id: '/minha-conta/seguranca'
      path: '/seguranca'
      fullPath: '/minha-conta/seguranca'
      preLoaderRoute: typeof MinhaContaSegurancaRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/lgpd': {
      id: '/minha-conta/lgpd'
      path: '/lgpd'
      fullPath: '/minha-conta/lgpd'
      preLoaderRoute: typeof MinhaContaLgpdRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/m/atendimento': {
      id: '/m/atendimento'
      path: '/m/atendimento'
      fullPath: '/m/atendimento'
      preLoaderRoute: typeof MAtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/plano-contas': {
      id: '/financeiro/plano-contas'
      path: '/plano-contas'
      fullPath: '/financeiro/plano-contas'
      preLoaderRoute: typeof FinanceiroPlanoContasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/notas-aberto': {
      id: '/financeiro/notas-aberto'
      path: '/notas-aberto'
      fullPath: '/financeiro/notas-aberto'
      preLoaderRoute: typeof FinanceiroNotasAbertoRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/maquininhas': {
      id: '/financeiro/maquininhas'
      path: '/maquininhas'
      fullPath: '/financeiro/maquininhas'
      preLoaderRoute: typeof FinanceiroMaquininhasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/fornecedores': {
      id: '/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/financeiro/fornecedores'
      preLoaderRoute: typeof FinanceiroFornecedoresRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dre': {
      id: '/financeiro/dre'
      path: '/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof FinanceiroDreRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/caixa': {
      id: '/financeiro/caixa'
      path: '/caixa'
      fullPath: '/financeiro/caixa'
      preLoaderRoute: typeof FinanceiroCaixaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/estoque/vendidos': {
      id: '/estoque/vendidos'
      path: '/vendidos'
      fullPath: '/estoque/vendidos'
      preLoaderRoute: typeof EstoqueVendidosRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/etiquetas': {
      id: '/estoque/etiquetas'
      path: '/etiquetas'
      fullPath: '/estoque/etiquetas'
      preLoaderRoute: typeof EstoqueEtiquetasRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/compras': {
      id: '/estoque/compras'
      path: '/compras'
      fullPath: '/estoque/compras'
      preLoaderRoute: typeof EstoqueComprasRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/atual': {
      id: '/estoque/atual'
      path: '/atual'
      fullPath: '/estoque/atual'
      preLoaderRoute: typeof EstoqueAtualRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/crm_/conversas': {
      id: '/crm_/conversas'
      path: '/crm/conversas'
      fullPath: '/crm/conversas'
      preLoaderRoute: typeof CrmConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/catalogo': {
      id: '/crm_/catalogo'
      path: '/crm/catalogo'
      fullPath: '/crm/catalogo'
      preLoaderRoute: typeof CrmCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/bot': {
      id: '/crm_/bot'
      path: '/crm/bot'
      fullPath: '/crm/bot'
      preLoaderRoute: typeof CrmBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite-loja/$token': {
      id: '/convite-loja/$token'
      path: '/convite-loja/$token'
      fullPath: '/convite-loja/$token'
      preLoaderRoute: typeof ConviteLojaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/loja': {
      id: '/configuracoes/loja'
      path: '/loja'
      fullPath: '/configuracoes/loja'
      preLoaderRoute: typeof ConfiguracoesLojaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/api/export-data': {
      id: '/api/export-data'
      path: '/api/export-data'
      fullPath: '/api/export-data'
      preLoaderRoute: typeof ApiExportDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-metrics': {
      id: '/api/admin-metrics'
      path: '/api/admin-metrics'
      fullPath: '/api/admin-metrics'
      preLoaderRoute: typeof ApiAdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite/$token': {
      id: '/aceitar-convite/$token'
      path: '/aceitar-convite/$token'
      fullPath: '/aceitar-convite/$token'
      preLoaderRoute: typeof AceitarConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt/$id': {
      id: '/api/receipt/$id'
      path: '/api/receipt/$id'
      fullPath: '/api/receipt/$id'
      preLoaderRoute: typeof ApiReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote/$id': {
      id: '/api/quote/$id'
      path: '/api/quote/$id'
      fullPath: '/api/quote/$id'
      preLoaderRoute: typeof ApiQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/os-public/$id': {
      id: '/api/os-public/$id'
      path: '/api/os-public/$id'
      fullPath: '/api/os-public/$id'
      preLoaderRoute: typeof ApiOsPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/$': {
      id: '/api/evolution/$'
      path: '/api/evolution/$'
      fullPath: '/api/evolution/$'
      preLoaderRoute: typeof ApiEvolutionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesLojaRoute: typeof ConfiguracoesLojaRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesLojaRoute: ConfiguracoesLojaRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface EstoqueRouteChildren {
  EstoqueAtualRoute: typeof EstoqueAtualRoute
  EstoqueComprasRoute: typeof EstoqueComprasRoute
  EstoqueEtiquetasRoute: typeof EstoqueEtiquetasRoute
  EstoqueMovimentacoesRoute: typeof EstoqueMovimentacoesRoute
  EstoqueVendidosRoute: typeof EstoqueVendidosRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueAtualRoute: EstoqueAtualRoute,
  EstoqueComprasRoute: EstoqueComprasRoute,
  EstoqueEtiquetasRoute: EstoqueEtiquetasRoute,
  EstoqueMovimentacoesRoute: EstoqueMovimentacoesRoute,
  EstoqueVendidosRoute: EstoqueVendidosRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface FinanceiroRouteChildren {
  FinanceiroCaixaRoute: typeof FinanceiroCaixaRoute
  FinanceiroDreRoute: typeof FinanceiroDreRoute
  FinanceiroFornecedoresRoute: typeof FinanceiroFornecedoresRoute
  FinanceiroMaquininhasRoute: typeof FinanceiroMaquininhasRoute
  FinanceiroNotasAbertoRoute: typeof FinanceiroNotasAbertoRoute
  FinanceiroPlanoContasRoute: typeof FinanceiroPlanoContasRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroCaixaRoute: FinanceiroCaixaRoute,
  FinanceiroDreRoute: FinanceiroDreRoute,
  FinanceiroFornecedoresRoute: FinanceiroFornecedoresRoute,
  FinanceiroMaquininhasRoute: FinanceiroMaquininhasRoute,
  FinanceiroNotasAbertoRoute: FinanceiroNotasAbertoRoute,
  FinanceiroPlanoContasRoute: FinanceiroPlanoContasRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface MinhaContaRouteChildren {
  MinhaContaLgpdRoute: typeof MinhaContaLgpdRoute
  MinhaContaSegurancaRoute: typeof MinhaContaSegurancaRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaLgpdRoute: MinhaContaLgpdRoute,
  MinhaContaSegurancaRoute: MinhaContaSegurancaRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

interface RelatoriosRouteChildren {
  RelatoriosChurnRoute: typeof RelatoriosChurnRoute
  RelatoriosComissoesRoute: typeof RelatoriosComissoesRoute
  RelatoriosCrescimentoRoute: typeof RelatoriosCrescimentoRoute
  RelatoriosVipRoute: typeof RelatoriosVipRoute
}

const RelatoriosRouteChildren: RelatoriosRouteChildren = {
  RelatoriosChurnRoute: RelatoriosChurnRoute,
  RelatoriosComissoesRoute: RelatoriosComissoesRoute,
  RelatoriosCrescimentoRoute: RelatoriosCrescimentoRoute,
  RelatoriosVipRoute: RelatoriosVipRoute,
}

const RelatoriosRouteWithChildren = RelatoriosRoute._addFileChildren(
  RelatoriosRouteChildren,
)

interface ServicosRouteChildren {
  ServicosChecklistsRoute: typeof ServicosChecklistsRoute
  ServicosDashboardRoute: typeof ServicosDashboardRoute
  ServicosNovaRoute: typeof ServicosNovaRoute
  ServicosTecnicosRoute: typeof ServicosTecnicosRoute
  ServicosTermosRoute: typeof ServicosTermosRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosChecklistsRoute: ServicosChecklistsRoute,
  ServicosDashboardRoute: ServicosDashboardRoute,
  ServicosNovaRoute: ServicosNovaRoute,
  ServicosTecnicosRoute: ServicosTecnicosRoute,
  ServicosTermosRoute: ServicosTermosRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

interface VendasRouteChildren {
  VendasCalculadoraRoute: typeof VendasCalculadoraRoute
  VendasConsultaEstoqueRoute: typeof VendasConsultaEstoqueRoute
  VendasDeliveryRoute: typeof VendasDeliveryRoute
  VendasGarantiasRoute: typeof VendasGarantiasRoute
  VendasHistoricoRoute: typeof VendasHistoricoRoute
  VendasOrcamentosRoute: typeof VendasOrcamentosRoute
  VendasSimuladorRoute: typeof VendasSimuladorRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasCalculadoraRoute: VendasCalculadoraRoute,
  VendasConsultaEstoqueRoute: VendasConsultaEstoqueRoute,
  VendasDeliveryRoute: VendasDeliveryRoute,
  VendasGarantiasRoute: VendasGarantiasRoute,
  VendasHistoricoRoute: VendasHistoricoRoute,
  VendasOrcamentosRoute: VendasOrcamentosRoute,
  VendasSimuladorRoute: VendasSimuladorRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AfiliadosRoute: AfiliadosRoute,
  AgentesRoute: AgentesRoute,
  ApiKeysRoute: ApiKeysRoute,
  AssinarRoute: AssinarRoute,
  AtendimentoRoute: AtendimentoRoute,
  AuditLogRoute: AuditLogRoute,
  AutomacaoRoute: AutomacaoRoute,
  AutomacoesRoute: AutomacoesRoute,
  BroadcastRoute: BroadcastRoute,
  CaixaPdvRoute: CaixaPdvRoute,
  CalendarioRoute: CalendarioRoute,
  ClientesRoute: ClientesRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  CrmRoute: CrmRoute,
  EquipeRoute: EquipeRoute,
  EquipeLojaRoute: EquipeLojaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FiscalRoute: FiscalRoute,
  FunilRoute: FunilRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  InstagramRoute: InstagramRoute,
  IntegracoesRoute: IntegracoesRoute,
  InventarioRoute: InventarioRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  LojasRoute: LojasRoute,
  MensagensAgendadasRoute: MensagensAgendadasRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  NpsRoute: NpsRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRoute,
  PdvRoute: PdvRoute,
  PipelineRoute: PipelineRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  RegistroRoute: RegistroRoute,
  RelatoriosRoute: RelatoriosRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRouteWithChildren,
  StatusRoute: StatusRoute,
  TemplatesRoute: TemplatesRoute,
  TermosRoute: TermosRoute,
  VendasRoute: VendasRouteWithChildren,
  WhatsappRoute: WhatsappRoute,
  AceitarConviteTokenRoute: AceitarConviteTokenRoute,
  ApiAdminMetricsRoute: ApiAdminMetricsRoute,
  ApiExportDataRoute: ApiExportDataRoute,
  ConviteLojaTokenRoute: ConviteLojaTokenRoute,
  CrmBotRoute: CrmBotRoute,
  CrmCatalogoRoute: CrmCatalogoRoute,
  CrmConversasRoute: CrmConversasRoute,
  MAtendimentoRoute: MAtendimentoRoute,
  OrcamentoIdRoute: OrcamentoIdRoute,
  OsTermoIdRoute: OsTermoIdRoute,
  OsTrackIdRoute: OsTrackIdRoute,
  ReciboIdRoute: ReciboIdRoute,
  ApiEvolutionSplatRoute: ApiEvolutionSplatRoute,
  ApiOsPublicIdRoute: ApiOsPublicIdRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiQuoteIdRoute: ApiQuoteIdRoute,
  ApiReceiptIdRoute: ApiReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
