// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || "https://irjzfrhvjrvvwnxygufo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyanpmcmh2anJ2dndueHlndWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MjMwOTAsImV4cCI6MjA5MzQ5OTA5MH0.sAikO8-diO61Aimk49hd9mAIxcwrULPzrU0pKqUFXTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof globalThis !== "undefined" && typeof (globalThis as any).localStorage !== "undefined";

export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? (globalThis as any).localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});