// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htsjkvczxlrsfapkbidq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0c2prdmN6eGxyc2ZhcGtiaWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMDUwOTAsImV4cCI6MjA5Mjg4MTA5MH0.sQroXA9tjLK5vmGzMUb_ShJqo7tG2Uvzis_iTW0kXhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof globalThis !== "undefined" && typeof (globalThis as any).localStorage !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? (globalThis as any).localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});